[package]
name = "minustwo"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
primitive-types = "0.13.1"
clap = { version = "4", features = ["derive"] }
hex = "0.4.3"
alloy-primitives = "1.1.0"

[[bin]]
name = "minustwo"
path = "src/main.rs"
