use crate::errors::Error;
use crate::errors::opcode::OpcodeError;
use crate::machine::Machine;
use crate::opcodes::stack_ops::execute_stack_swap;
use crate::opcodes::{
    Opcode,
    arithmetic::{execute_arithmetic, execute_logical},
    control::execute_control,
    memory_ops::execute_memory,
    stack_ops::{execute_stack_duplicate, execute_stack_pop, execute_stack_push},
};

pub fn execute_opcode(machine: &mut Machine, opcode: usize) -> Result<(), Error> {
    match opcode {
        0x00 => execute_control(Opcode::STOP, machine),
        0x01 => execute_arithmetic(Opcode::ADD, machine),
        0x02 => execute_arithmetic(Opcode::SUB, machine),
        0x03 => execute_arithmetic(Opcode::MUL, machine),
        0x04 => execute_arithmetic(Opcode::DIV, machine),
        0x05 => execute_arithmetic(Opcode::SDIV, machine),
        0x06 => execute_arithmetic(Opcode::MOD, machine),
        0x07 => execute_arithmetic(Opcode::SMOD, machine),
        0x08 => execute_arithmetic(Opcode::ADDMOD, machine),
        0x09 => execute_arithmetic(Opcode::MULMOD, machine),
        0x0A => execute_arithmetic(Opcode::EXP, machine),
        0x0B => execute_arithmetic(Opcode::SIGNEXTEND, machine),
        0x10 => execute_logical(Opcode::LT, machine),
        0x11 => execute_logical(Opcode::SLT, machine),
        0x12 => execute_logical(Opcode::GT, machine),
        0x13 => execute_logical(Opcode::SGT, machine),
        0x14 => execute_logical(Opcode::EQ, machine),
        0x15 => execute_logical(Opcode::ISZERO, machine),
        0x16 => execute_logical(Opcode::AND, machine),
        0x17 => execute_logical(Opcode::OR, machine),
        0x18 => execute_logical(Opcode::XOR, machine),
        0x19 => execute_logical(Opcode::NOT, machine),
        0x50 => execute_stack_pop(Opcode::POP, machine),
        0x51 => execute_memory(Opcode::MLOAD, machine),
        0x52 => execute_memory(Opcode::MSTORE, machine),
        0x60 => execute_stack_push(Opcode::PUSH1, 1, machine),
        0x61 => execute_stack_push(Opcode::PUSH2, 2, machine),
        0x62 => execute_stack_push(Opcode::PUSH3, 3, machine),
        0x63 => execute_stack_push(Opcode::PUSH4, 4, machine),
        0x64 => execute_stack_push(Opcode::PUSH5, 5, machine),
        0x65 => execute_stack_push(Opcode::PUSH6, 6, machine),
        0x66 => execute_stack_push(Opcode::PUSH7, 7, machine),
        0x67 => execute_stack_push(Opcode::PUSH8, 8, machine),
        0x68 => execute_stack_push(Opcode::PUSH9, 9, machine),
        0x69 => execute_stack_push(Opcode::PUSH10, 10, machine),
        0x6A => execute_stack_push(Opcode::PUSH11, 11, machine),
        0x6B => execute_stack_push(Opcode::PUSH12, 12, machine),
        0x6C => execute_stack_push(Opcode::PUSH13, 13, machine),
        0x6D => execute_stack_push(Opcode::PUSH14, 14, machine),
        0x6E => execute_stack_push(Opcode::PUSH15, 15, machine),
        0x6F => execute_stack_push(Opcode::PUSH16, 16, machine),
        0x70 => execute_stack_push(Opcode::PUSH17, 17, machine),
        0x71 => execute_stack_push(Opcode::PUSH18, 18, machine),
        0x72 => execute_stack_push(Opcode::PUSH19, 19, machine),
        0x73 => execute_stack_push(Opcode::PUSH20, 20, machine),
        0x74 => execute_stack_push(Opcode::PUSH21, 21, machine),
        0x75 => execute_stack_push(Opcode::PUSH22, 22, machine),
        0x76 => execute_stack_push(Opcode::PUSH23, 23, machine),
        0x77 => execute_stack_push(Opcode::PUSH24, 24, machine),
        0x78 => execute_stack_push(Opcode::PUSH25, 25, machine),
        0x79 => execute_stack_push(Opcode::PUSH26, 26, machine),
        0x7A => execute_stack_push(Opcode::PUSH27, 27, machine),
        0x7B => execute_stack_push(Opcode::PUSH28, 28, machine),
        0x7C => execute_stack_push(Opcode::PUSH29, 29, machine),
        0x7D => execute_stack_push(Opcode::PUSH30, 30, machine),
        0x7E => execute_stack_push(Opcode::PUSH31, 31, machine),
        0x7F => execute_stack_push(Opcode::PUSH32, 32, machine),
        0x80 => execute_stack_duplicate(Opcode::DUP1, 1, machine),
        0x81 => execute_stack_duplicate(Opcode::DUP2, 2, machine),
        0x82 => execute_stack_duplicate(Opcode::DUP3, 3, machine),
        0x83 => execute_stack_duplicate(Opcode::DUP4, 4, machine),
        0x84 => execute_stack_duplicate(Opcode::DUP5, 5, machine),
        0x85 => execute_stack_duplicate(Opcode::DUP6, 6, machine),
        0x86 => execute_stack_duplicate(Opcode::DUP7, 7, machine),
        0x87 => execute_stack_duplicate(Opcode::DUP8, 8, machine),
        0x88 => execute_stack_duplicate(Opcode::DUP9, 9, machine),
        0x89 => execute_stack_duplicate(Opcode::DUP10, 10, machine),
        0x8A => execute_stack_duplicate(Opcode::DUP11, 11, machine),
        0x8B => execute_stack_duplicate(Opcode::DUP12, 12, machine),
        0x8C => execute_stack_duplicate(Opcode::DUP13, 13, machine),
        0x8D => execute_stack_duplicate(Opcode::DUP14, 14, machine),
        0x8E => execute_stack_duplicate(Opcode::DUP15, 15, machine),
        0x8F => execute_stack_duplicate(Opcode::DUP16, 16, machine),
        0x90 => execute_stack_swap(Opcode::SWAP1, 1, machine),
        0x91 => execute_stack_swap(Opcode::SWAP2, 2, machine),
        0x92 => execute_stack_swap(Opcode::SWAP3, 3, machine),
        0x93 => execute_stack_swap(Opcode::SWAP4, 4, machine),
        0x94 => execute_stack_swap(Opcode::SWAP5, 5, machine),
        0x95 => execute_stack_swap(Opcode::SWAP6, 6, machine),
        0x96 => execute_stack_swap(Opcode::SWAP7, 7, machine),
        0x97 => execute_stack_swap(Opcode::SWAP8, 8, machine),
        0x98 => execute_stack_swap(Opcode::SWAP9, 9, machine),
        0x99 => execute_stack_swap(Opcode::SWAP10, 10, machine),
        0x9A => execute_stack_swap(Opcode::SWAP11, 11, machine),
        0x9B => execute_stack_swap(Opcode::SWAP12, 12, machine),
        0x9C => execute_stack_swap(Opcode::SWAP13, 13, machine),
        0x9D => execute_stack_swap(Opcode::SWAP14, 14, machine),
        0x9E => execute_stack_swap(Opcode::SWAP15, 15, machine),
        0x9F => execute_stack_swap(Opcode::SWAP16, 16, machine),
        _ => Err(Error::OpcodeError(OpcodeError::InvalidOpcode(opcode))), // Handle unknown opcodes
    }?;
    println!("After executing {:02X?}:\n{}", opcode, machine.stack);
    Ok(())
}
